from netconfiglint.core.model.config import (
    ACL,
    BGPAddressFamily,
    BGPPeer,
    BGPProcess,
    DeviceConfig,
    Interface,
    OSPFNetwork,
    OSPFProcess,
    PrefixList,
    RoutePolicy,
    StaticRoute,
    Vlan,
    VpnInstance,
)

__all__ = [
    "ACL",
    "BGPAddressFamily",
    "BGPPeer",
    "BGPProcess",
    "DeviceConfig",
    "Interface",
    "OSPFNetwork",
    "OSPFProcess",
    "PrefixList",
    "RoutePolicy",
    "StaticRoute",
    "Vlan",
    "VpnInstance",
]
